[[news]]
date = "2025-12"
content = "Our works have been accepted by JMIR Medical Informatics and IEEE JBHI ðŸŽ‰"

[[news]]
date = "2025-11"
content = "I was awarded Best Student Paper Finalist at AMIA 2025, one of only eight in the world, and we were the only one from outside the United States ðŸŽ‰"

[[news]]
date = "2025-09"
content = "I received the May 4th Scholarship and some honors from Peking University ðŸŽ‰"