
[[news]]
date = "2025-11"
content = "I was awarded the Student Paper Competition Finalist at AMIA 2025 Annual Symposium, only eight in the world, and we were the only one from outside the United States. ðŸŽ‰"

[[news]]
date = "2025-11"
content = "Our works have been accepted by JMIR Medical Informatics and IEEE JBHI. ðŸŽ‰"


[[news]]
date = "2025-09"
content = "I received the May 4th Scholarship and some honors from Peking University. ðŸŽ‰"

[[news]]
date = "2025-07"
content = "I have assumed the position of Deputy Chief Editor of the Official WeChat Account of Peking University. ðŸŽ‰"

[[news]]
date = "2025-06"
content = "Our work has been accepted by JAMIA Open. ðŸŽ‰"

[[news]]
date = "2024-12"
content = "Our work has been accepted by Kidney Medicine. ðŸŽ‰"

[[news]]
date = "2024-09"
content = "I received the National Scholarship and some honors from Peking University. ðŸŽ‰"

[[news]]
date = "2024-07"
content = "I have assumed the position of Chief Editor of the Backend Team for the Official WeChat Account of Peking University. ðŸŽ‰"

[[news]]
date = "2024-05"
content = "Our work has been accepted by SPJ Health Data Science. ðŸŽ‰"